### ISSUE TITLE
Cooperating on improve CocoR parsers

### ISSUE THREAD

**Issue by mingodad** [sebdeveloper6952/rust-cocor#1]
Hello !
I'm making some improvements to CocoR and think that we can cooperate somehow here is my repository https://github.com/mingodad/CocoR-CPP and here I'm talking with another users about some improvements https://github.com/rochus-keller/EbnfStudio/issues/2 and https://github.com/SSW-CocoR/CocoR-CPP/issues/1 .

Cheers !

**Comment by sebdeveloper6952** [comment]
Hi @mingodad , thank your for considering me for your project. It looks like it is really feature complete. I made my project as part of a university course, and it is ugly but I certainly learned a lot this past few months about the frontend of a compiler and CocoR. I would be more than happy if I can contribute to your project in any way.

I had a look at the links you shared with me and to be honest, you guys are way ahead of me. Having said that, I want to reiterate that I am interested in contributing.

Is there anything in specific I can start taking a look at?

Thank you for considering me.

**Comment by mingodad** [comment]
Hello Sebas !
I was thinking that you was trying to implement the full CocoR in Rust and that we could interchange ideas like probably you also know that there is another attempts to implement CocoR in other languages.

But it seems that your scope is rather limited to your university course, any way good luck with it and thanks !
 
Cheers !

**Comment by sebdeveloper6952** [comment]
Hi Domingo!

Yes you are correct in that my scope is limited. Maybe in some feature we could exchange some more ideas and contribute to improve CoCoR. I will star your project to keep it in sight!

Cheers,
Sebas
